### ISSUE TITLE
Limit and offset is not translated to FIRST and SKIP

### ISSUE THREAD

**Issue by RodolfoSilva** [nakagami/ecto_firebird#1]
Right now we are not able to apply the ecto `first` and `skip`
The SQL generated have a 'LIMIT' and 'OFFSET' instead. 

https://razorsql.com/articles/firebird_limit_rows.html

**Comment by nakagami** [comment]
Thanks for the report.
I don't use Ecto usually, so that helps a lot.

Only  test for SQL statement generation, but is this correct?
https://github.com/nakagami/ecto_firebird/commit/bd29bea83dee525fc85f71ae6d3ed059e885dee2

I will merge it if it looks good.

**Comment by RodolfoSilva** [comment]
@nakagami no this is not correct, in the Firebird the LIMIT comes before the selected columns. It's very weird but:

In the case of:
https://github.com/nakagami/ecto_firebird/commit/bd29bea83dee525fc85f71ae6d3ed059e885dee2#diff-684b16320dca0a6bb482b29d7f2b619c7e1d23ab152cab0c984dbaf01927df84L690-L692

The generated query should be:

```patch
- SELECT name FROM sqlite_master WHERE type='table' AND name=? FIRST 1"
+ SELECT FIRST 1 name FROM sqlite_master WHERE type='table' AND name=?"
```

And for this case:

https://github.com/nakagami/ecto_firebird/commit/bd29bea83dee525fc85f71ae6d3ed059e885dee2#diff-0811556ff6b41dcd9314f62eeb4c5df67f0e2a3c8c5540f1ab35c6e43459b245L561-R562

```patch
- SELECT name FROM sqlite_master WHERE type='table' AND name=? FIRST 1"
+ SELECT FIRST 3 SKIP 5 1 FROM "schema" AS s0"
```

**Comment by RodolfoSilva** [comment]
Firebird select spec:

https://firebirdsql.org/refdocs/langrefupd20-select.html#langrefupd20-first-skip

```
SELECT [FIRST (<int-expr>)] [SKIP (<int-expr>)] <columns> FROM ...

<int-expr>  ::=  Any expression evaluating to an integer.
<columns>   ::=  The usual output column specifications.
```

**Comment by nakagami** [comment]
Ah, you are right.
I understand. I'll try to fix it.

**Comment by nakagami** [comment]
https://github.com/nakagami/ecto_firebird/pull/2
If it looks about right, I will merge it.

**Comment by nakagami** [comment]
We merged because it can't get any worse than it is now.
